/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.galeriaarte.view;

import javax.swing.JOptionPane;

/**
 *
 * @author SANTIAGO
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuPintura = new javax.swing.JMenu();
        jMenuItemAgregarPintura = new javax.swing.JMenuItem();
        jMenuItemListarPintura = new javax.swing.JMenuItem();
        jMenuItemActualizarPintura = new javax.swing.JMenuItem();
        jMenuItemEliminarPintura = new javax.swing.JMenuItem();
        jMenuEscultura = new javax.swing.JMenu();
        jMenuItemAgregarEscultura = new javax.swing.JMenuItem();
        jMenuItemListarEscultura = new javax.swing.JMenuItem();
        jMenuItemActualizarEscultura = new javax.swing.JMenuItem();
        jMenuItemEliminarEscultura = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenuPintura.setText("Pintura");

        jMenuItemAgregarPintura.setText("Agregar Pintura");
        jMenuItemAgregarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarPinturaActionPerformed(evt);
            }
        });
        jMenuPintura.add(jMenuItemAgregarPintura);

        jMenuItemListarPintura.setText("Listar Pintura");
        jMenuItemListarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarPinturaActionPerformed(evt);
            }
        });
        jMenuPintura.add(jMenuItemListarPintura);

        jMenuItemActualizarPintura.setText("Actualizar Pintura");
        jMenuItemActualizarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarPinturaActionPerformed(evt);
            }
        });
        jMenuPintura.add(jMenuItemActualizarPintura);

        jMenuItemEliminarPintura.setText("Eliminar Pintura");
        jMenuItemEliminarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarPinturaActionPerformed(evt);
            }
        });
        jMenuPintura.add(jMenuItemEliminarPintura);

        jMenuBar1.add(jMenuPintura);

        jMenuEscultura.setText("Escultura");

        jMenuItemAgregarEscultura.setText("Agregar Escultura");
        jMenuItemAgregarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarEsculturaActionPerformed(evt);
            }
        });
        jMenuEscultura.add(jMenuItemAgregarEscultura);

        jMenuItemListarEscultura.setText("Listar Escultura");
        jMenuItemListarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarEsculturaActionPerformed(evt);
            }
        });
        jMenuEscultura.add(jMenuItemListarEscultura);

        jMenuItemActualizarEscultura.setText("Actualizar Escultura");
        jMenuItemActualizarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarEsculturaActionPerformed(evt);
            }
        });
        jMenuEscultura.add(jMenuItemActualizarEscultura);

        jMenuItemEliminarEscultura.setText("Eliminar Escultura");
        jMenuItemEliminarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarEsculturaActionPerformed(evt);
            }
        });
        jMenuEscultura.add(jMenuItemEliminarEscultura);

        jMenuBar1.add(jMenuEscultura);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercade.setText("Acerca de...");
        jMenuItemAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercadeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercade);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercadeActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por Santiago Arciniegas - 2220221016\n" + "Daniel Mauricio Álvarez Morales - 2420211008\n" + "Brayan Santiago Cartagena Díaz - 2220221056\n" + "Julián Camilo Aranguren Herrán - 2220231103");
    }//GEN-LAST:event_jMenuItemAcercadeActionPerformed

    private void jMenuItemAgregarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarPinturaActionPerformed
        GUIAgregarPintura gui = new GUIAgregarPintura();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarPinturaActionPerformed

    private void jMenuItemListarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarPinturaActionPerformed
        GUIListarPintura gui = new GUIListarPintura();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarPinturaActionPerformed

    private void jMenuItemActualizarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarPinturaActionPerformed
        GUIActualizarPintura gui = new GUIActualizarPintura();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarPinturaActionPerformed

    private void jMenuItemEliminarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarPinturaActionPerformed
        GUIEliminarPintura gui = new GUIEliminarPintura();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarPinturaActionPerformed

    private void jMenuItemAgregarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarEsculturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgregarEsculturaActionPerformed

    private void jMenuItemListarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarEsculturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListarEsculturaActionPerformed

    private void jMenuItemActualizarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarEsculturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemActualizarEsculturaActionPerformed

    private void jMenuItemEliminarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarEsculturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEliminarEsculturaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEscultura;
    private javax.swing.JMenuItem jMenuItemAcercade;
    private javax.swing.JMenuItem jMenuItemActualizarEscultura;
    private javax.swing.JMenuItem jMenuItemActualizarPintura;
    private javax.swing.JMenuItem jMenuItemAgregarEscultura;
    private javax.swing.JMenuItem jMenuItemAgregarPintura;
    private javax.swing.JMenuItem jMenuItemEliminarEscultura;
    private javax.swing.JMenuItem jMenuItemEliminarPintura;
    private javax.swing.JMenuItem jMenuItemListarEscultura;
    private javax.swing.JMenuItem jMenuItemListarPintura;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuPintura;
    // End of variables declaration//GEN-END:variables
}
